declare module 'bjork_react-hookup/core/useBoolean'
declare module 'bjork_react-hookup/core/useArray'
declare module 'bjork_react-hookup/core/useAsync'
declare module './useAsync'
declare module 'bjork_react-hookup/core/useReduceMotion'
declare module 'react-loader-spinner'